project_id = "owgkhkxsaeizgwxebarh"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[functions]
enabled = true
port = 54327

[functions.verify_user_code]
verify_jwt = false