project_id = "owgkhkxsaeizgwxebarh"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[functions]
enabled = true
port = 54327

[functions.add_device]
verify_jwt = true

[functions.get_alarm_history]
verify_jwt = true

[functions.get_device_status]
verify_jwt = true

[functions.remove_device]
verify_jwt = true

[functions.save_fcm_token]
verify_jwt = true

[functions.shelly_webhook]
verify_jwt = false

[functions.shelly_cloud_api]
verify_jwt = false

[functions.test_login]
verify_jwt = false

[functions.verify_user_code]
verify_jwt = false

[functions.test_alarm]
verify_jwt = false

[functions.shelly_fleet_manager]
verify_jwt = false