// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owgkhkxsaeizgwxebarh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93Z2toa3hzYWVpemd3eGViYXJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTA0NTUsImV4cCI6MjA2NzQ4NjQ1NX0.jBpM_u60mg0k6x5gGwFvru87fqJdRFGSWyTGMO2wM0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with standard web configuration
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});